org: elmundio87
app: forekast
service: forekast

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: eu-west-2

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
